/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedListeningRouteImport } from './routes/_authenticated/listening'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedVocabularyRouteImport } from './routes/_authenticated/vocabulary'
import { Route as AuthenticatedWritingRouteImport } from './routes/_authenticated/writing'
import { Route as ApiCoachStreamRouteImport } from './routes/api/coach-stream'
import { Route as ApiSpeechRouteImport } from './routes/api/speech'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedLearningIndexRouteImport } from './routes/_authenticated/learning/index'
import { Route as AuthenticatedLearningLessonIdRouteImport } from './routes/_authenticated/learning/$lessonId'
import { Route as AuthenticatedLearningFinalTestRouteImport } from './routes/_authenticated/learning/final-test'
import { Route as AuthenticatedLearningReviewRouteImport } from './routes/_authenticated/learning/review'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListeningRoute = AuthenticatedListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVocabularyRoute = AuthenticatedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWritingRoute = AuthenticatedWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCoachStreamRoute = ApiCoachStreamRouteImport.update({
  id: '/api/coach-stream',
  path: '/api/coach-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechRoute = ApiSpeechRouteImport.update({
  id: '/api/speech',
  path: '/api/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearningIndexRoute =
  AuthenticatedLearningIndexRouteImport.update({
    id: '/learning/',
    path: '/learning/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearningLessonIdRoute =
  AuthenticatedLearningLessonIdRouteImport.update({
    id: '/learning/$lessonId',
    path: '/learning/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearningFinalTestRoute =
  AuthenticatedLearningFinalTestRouteImport.update({
    id: '/learning/final-test',
    path: '/learning/final-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearningReviewRoute =
  AuthenticatedLearningReviewRouteImport.update({
    id: '/learning/review',
    path: '/learning/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/listening': typeof AuthenticatedListeningRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/writing': typeof AuthenticatedWritingRoute
  '/api/coach-stream': typeof ApiCoachStreamRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/learning/$lessonId': typeof AuthenticatedLearningLessonIdRoute
  '/learning/final-test': typeof AuthenticatedLearningFinalTestRoute
  '/learning/review': typeof AuthenticatedLearningReviewRoute
  '/learning/': typeof AuthenticatedLearningIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/listening': typeof AuthenticatedListeningRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/writing': typeof AuthenticatedWritingRoute
  '/api/coach-stream': typeof ApiCoachStreamRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/learning/$lessonId': typeof AuthenticatedLearningLessonIdRoute
  '/learning/final-test': typeof AuthenticatedLearningFinalTestRoute
  '/learning/review': typeof AuthenticatedLearningReviewRoute
  '/learning': typeof AuthenticatedLearningIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/listening': typeof AuthenticatedListeningRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/_authenticated/vocabulary': typeof AuthenticatedVocabularyRoute
  '/_authenticated/writing': typeof AuthenticatedWritingRoute
  '/api/coach-stream': typeof ApiCoachStreamRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/learning/$lessonId': typeof AuthenticatedLearningLessonIdRoute
  '/_authenticated/learning/final-test': typeof AuthenticatedLearningFinalTestRoute
  '/_authenticated/learning/review': typeof AuthenticatedLearningReviewRoute
  '/_authenticated/learning/': typeof AuthenticatedLearningIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coach'
    | '/dashboard'
    | '/listening'
    | '/onboarding'
    | '/premium'
    | '/progress'
    | '/teacher'
    | '/vocabulary'
    | '/writing'
    | '/api/coach-stream'
    | '/api/speech'
    | '/api/transcribe'
    | '/learning/$lessonId'
    | '/learning/final-test'
    | '/learning/review'
    | '/learning/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coach'
    | '/dashboard'
    | '/listening'
    | '/onboarding'
    | '/premium'
    | '/progress'
    | '/teacher'
    | '/vocabulary'
    | '/writing'
    | '/api/coach-stream'
    | '/api/speech'
    | '/api/transcribe'
    | '/learning/$lessonId'
    | '/learning/final-test'
    | '/learning/review'
    | '/learning'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/listening'
    | '/_authenticated/onboarding'
    | '/_authenticated/premium'
    | '/_authenticated/progress'
    | '/_authenticated/teacher'
    | '/_authenticated/vocabulary'
    | '/_authenticated/writing'
    | '/api/coach-stream'
    | '/api/speech'
    | '/api/transcribe'
    | '/_authenticated/learning/$lessonId'
    | '/_authenticated/learning/final-test'
    | '/_authenticated/learning/review'
    | '/_authenticated/learning/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiCoachStreamRoute: typeof ApiCoachStreamRoute
  ApiSpeechRoute: typeof ApiSpeechRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listening': {
      id: '/_authenticated/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof AuthenticatedListeningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocabulary': {
      id: '/_authenticated/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AuthenticatedVocabularyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/writing': {
      id: '/_authenticated/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof AuthenticatedWritingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/coach-stream': {
      id: '/api/coach-stream'
      path: '/api/coach-stream'
      fullPath: '/api/coach-stream'
      preLoaderRoute: typeof ApiCoachStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech': {
      id: '/api/speech'
      path: '/api/speech'
      fullPath: '/api/speech'
      preLoaderRoute: typeof ApiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learning/': {
      id: '/_authenticated/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof AuthenticatedLearningIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning/$lessonId': {
      id: '/_authenticated/learning/$lessonId'
      path: '/learning/$lessonId'
      fullPath: '/learning/$lessonId'
      preLoaderRoute: typeof AuthenticatedLearningLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning/final-test': {
      id: '/_authenticated/learning/final-test'
      path: '/learning/final-test'
      fullPath: '/learning/final-test'
      preLoaderRoute: typeof AuthenticatedLearningFinalTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning/review': {
      id: '/_authenticated/learning/review'
      path: '/learning/review'
      fullPath: '/learning/review'
      preLoaderRoute: typeof AuthenticatedLearningReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedListeningRoute: typeof AuthenticatedListeningRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedVocabularyRoute: typeof AuthenticatedVocabularyRoute
  AuthenticatedWritingRoute: typeof AuthenticatedWritingRoute
  AuthenticatedLearningLessonIdRoute: typeof AuthenticatedLearningLessonIdRoute
  AuthenticatedLearningFinalTestRoute: typeof AuthenticatedLearningFinalTestRoute
  AuthenticatedLearningReviewRoute: typeof AuthenticatedLearningReviewRoute
  AuthenticatedLearningIndexRoute: typeof AuthenticatedLearningIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedListeningRoute: AuthenticatedListeningRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedVocabularyRoute: AuthenticatedVocabularyRoute,
  AuthenticatedWritingRoute: AuthenticatedWritingRoute,
  AuthenticatedLearningLessonIdRoute: AuthenticatedLearningLessonIdRoute,
  AuthenticatedLearningFinalTestRoute: AuthenticatedLearningFinalTestRoute,
  AuthenticatedLearningReviewRoute: AuthenticatedLearningReviewRoute,
  AuthenticatedLearningIndexRoute: AuthenticatedLearningIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiCoachStreamRoute: ApiCoachStreamRoute,
  ApiSpeechRoute: ApiSpeechRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
